-- V4__add_match_categories.sql

-- 1. Ustvarimo tabelo za kategorije ujemanj
CREATE TABLE match_categories (
                                  id INTEGER PRIMARY KEY CHECK (id BETWEEN 1 AND 5),
                                  category_name TEXT NOT NULL,
                                  description TEXT NOT NULL
);

-- 2. Vstavimo vseh 5 kategorij
INSERT INTO match_categories (id, category_name, description) VALUES
                                                                  (1, 'Maksimalno ujemanje', 'Sam medosebni odnos zaradi dobrega ujemanja ne prinaša veliko stresa. Komunikacija med partnerjema je enostavna, sporazumeta se lahko že neverbalno. Večino časa vesta, kaj lahko pričakujeta drug od drugega. Presenečenj v odnosu je bolj malo, všeč so jima podobne stvari. Posledično je manjša verjetnost za konflikte in potrebnega je manj prilagajanja. Če osebama ustreza rutina in jima nepredvidljivost pomeni obremenitev, je to zanju idealen odnos. V nasprotnem primeru pa lahko pride do zdolgočasenosti, saj odnos ne ponuja vira razburljivosti. Le-to je zato potrebno poiskati v drugih skupnih dejavnostih. Težave lahko nastanejo, kadar si en partner želi dobro strukturiran odnos, drugi pa ravno obratno, saj je v tem primeru en partner zelo zadovoljen, drugi pa zelo nezadovoljen. V takih primerih je potrebna še posebna potrpežljivost in veliko razumevanja.'),
                                                                  (2, 'Majhne razlike', 'V večini situacij je odnos predvidljiv. Partnerja vesta, kaj lahko drug od drugega pričakujeta, vendar občasno drug drugega še vedno zmoreta presenetiti. Komunikacija je večino časa dobra, redkeje lahko pride tudi do nesporazumov in konfliktov. Če si partnerja želita ustaljenega, predvidljivega odnosa, potem sta večino časa zadovoljna. V trenutkih, ko zaradi manjšega neujemanja lahko pride do konfliktov, pa so ti konflikti lahko precej stresni, saj jih je v odnosu manj in v takih primerih še pridobijo na vrednosti. Za partnerje, ki si želijo bolj nepredvidljive zveze, bo tak odnos večino časa dolgočasen. Potrebno bo več domišljije, da bi se dolgočasje razbijalo. Brez posebne pozornosti bodo taki trenutki zadovoljstva bolj redki in vsekakor ne bodo v dovoljšnji meri začinili odnosa, kjer si partnerja želita raznolikosti. Bo pa tak odnos kljub vsemu manj viharen, saj sta si parterja podobna.'),
                                                                  (3, 'Srednje razlike', 'Odnos je v nekaterih ozirih predvidljiv, v drugih spet nepredvidljiv. Odnos s povprečnimi razlikami je za vse partnerje, ki si želijo rutino ali popolno nepredvidljivost, enako stresen in pogosto dovoljuje resne konflikte. Za tiste, željne rutine, predstavlja stres vsak trenutek, ko zaradi razlik prihaja do neskladij. Obratno je pri tistih, željnih raznolikosti, ki se lahko začnejo dolgočasiti. Tak odnos prinaša precej dobro rešitev, kadar gre za partnerja s povsem različnimi pogledi na zvezo, saj sta oba približno enako zadovoljna – eden v trenutkih strukturiranosti in rutine, drugi v zanimivi nepredvidljivosti. Vsekakor pa tak odnos narekuje veliko mero potrpežljivosti in tolerantnosti do drugačnosti partnerja, pa tudi ustrezno razvite komunikacijske spretnosti, da lahko obstoječe razlike partnerja med seboj mirno premostita. Z vlaganjem napora in truda lahko tak odnos postane dolgoročno perspektiven, ker kljub neki srednji rutini omogoča občasno drugačnost, kar začini odnos. Bo pa zelo verjetno tak odnos po prvi fazi zaljubljenosti moral skozi mnoge preizkušnje. Če jih partnerja uspešno prestaneta, lahko tak odnos z leti postane lepši in bolj poln razumevanja.'),
                                                                  (4, 'Velike razlike', 'Odnos prinaša več raznolikosti kot podobnosti. Veliko je neskladij in nestrinjanj, ki zahtevajo veliko mero potrpežljivosti in zaupanja. Tak odnos precej dobro ustreza osebam, ki prisegajo na zanimiv, nepredvidljiv odnos s partnerjem. Kljub temu se še vedno lahko občasno izgubijo v nezanimivosti odnosa, kadar prihaja do daljših obdobij velike usklajenosti. Za osebe, ki si želijo predvidljivega, kontroliranega odnosa, je te vrste odnos lahko precej stresen in zahteva dobršno mero prilagajanja, ki jim predstavlja stresne situacije. Vsi tisti, ki prisegajo na adrenalin v odnosu, ga bodo tukaj zagotovo našli. Če pa želimo tak odnos obdržati, bo potrebno po začetni fazi zaljubljenosti veliko delati na razvijanju ustrezne komunikacije in potrpežljivosti pri sprejemanju in navajanju na drugačnost partnerja. Za obstoj takega odnosa se bosta morala oba s partnerjem precej potruditi.'),
                                                                  (5, 'Neujemanje', 'Odnos s tako velikimi razlikami je ponavadi zelo pester in nepredvidljiv. Pogosti so konflikti zaradi različnih pričakovanj. Potrebnega je veliko razumevanja in usklajevanja. Komunikacija je lahko večkrat težavna. Ponavadi je tak odnos zelo energičen in poln strasti. Veliko je izzivov. Partnerja, ki nočeta rutine in uživata v nepredvidljivosti, bosta v takem odnosu zelo zadovoljna, če bosta le znala uskladiti najpomembnejše stvari v odnosu (zaupanje, naloge, komunikacija).  Za osebe, ki prisegajo na strukturiranost, je tak odnos lahko zelo obremenjujoč in predstavlja velik vir stresa ter zelo verjetno v takem odnosu ne bodo mogli vztrajati dlje časa, najverjetneje se bo tak odnos burno zaključil v obdobju, ko začetna faza zaljubljenosti mine. Samo najbolj zrelim osebam lahko tak odnos tudi dolgoročno uspe. Če pa jim to uspe, zna postati tak odnos zadovoljujoč, saj vsakemu posamezniku omogoča obdržati ustrezno mero drugačnosti in posebnosti.');

-- 3. Dodamo stolpec category_id v match_results
ALTER TABLE match_results
    ADD COLUMN category_id INTEGER;

-- 4. Dodamo zunanji ključ na match_categories
ALTER TABLE match_results
    ADD CONSTRAINT fk_match_category FOREIGN KEY (category_id)
        REFERENCES match_categories(id);